// This file is auto-generated by @hey-api/openapi-ts

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusResponses = {
    /**
     * Default Response
     */
    200: {
        status: string;
    };
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3333' | (string & {});
};